/**
 * Created with IntelliJ IDEA.
 * User: NCraig
 * Date: 8/16/13
 * Time: 4:37 PM
 * To change this template use File | Settings | File Templates.
 */

package   com.cwh.wb.WhiteBuffaloConfig;

import com.cwh.slotstoolbox2.reels.ReelsConfig;
import java.util.*;

public class WhiteBuffaloReelsConfig implements ReelsConfig {

	private static final Map<Object, Map<Integer,List<String>>> reels = new HashMap<Object, Map<Integer,List<String>>>();
	
	private static final Map<Object, Map<Integer,List<Integer>>> initStops = new HashMap<Object, Map<Integer,List<Integer>>>();

	static {
		// 92% Paytable
		getReels().put(WhiteBuffaloRTP.RTP_92, new HashMap<Integer, List<String>>());
		getReels().get(WhiteBuffaloRTP.RTP_92).put(1, Arrays.asList(
				WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, 
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, 
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_QUEEN, 
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, 
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_LOGO, 
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_JACK, 
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_JACK, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, 
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, 
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, 
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, 
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK, 
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, 
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_JACK, 
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK));
		getReels().get(WhiteBuffaloRTP.RTP_92).put(2, Arrays.asList(
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, 
				WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, 
				WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_BONUS, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING, 
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_ACE, 
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_BONUS, 
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, 
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_KING, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_BONUS, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, 
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, 
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, 
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_ACE, 
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_ACE, 
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, 
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, 
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, 
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, 
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING));
		getReels().get(WhiteBuffaloRTP.RTP_92).put(3, Arrays.asList(
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_WILD,
				WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_WILD, 
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, 
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN, 
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_ACE, 
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_BONUS, 
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, 
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, 
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, 
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_GODDESS, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_GODDESS));
		getReels().get(WhiteBuffaloRTP.RTP_92).put(4, Arrays.asList(
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, 
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD,
				WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, 
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_URN, 
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_GODDESS, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN, 
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, 
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_KING, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, 
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, 
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK));
		getReels().get(WhiteBuffaloRTP.RTP_92).put(5, Arrays.asList(
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN));

		// 94% Paytable
		getReels().put(WhiteBuffaloRTP.RTP_94, new HashMap<Integer, List<String>>());
		getReels().get(WhiteBuffaloRTP.RTP_94).put(1, Arrays.asList(
				WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK));
		getReels().get(WhiteBuffaloRTP.RTP_94).put(2, Arrays.asList(
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD,
				WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_BONUS, 
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, 
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, 
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_GODDESS, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING));
		getReels().get(WhiteBuffaloRTP.RTP_94).put(3, Arrays.asList(
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_WILD,
				WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_WILD,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_GODDESS));
		getReels().get(WhiteBuffaloRTP.RTP_94).put(4, Arrays.asList(
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD,
				WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK));
		getReels().get(WhiteBuffaloRTP.RTP_94).put(5, Arrays.asList(
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_JACK, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, 
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_ACE, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_QUEEN, 
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_URN, 
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN));

		// 95% Paytable
		getReels().put(WhiteBuffaloRTP.RTP_95, new HashMap<Integer, List<String>>());
		getReels().get(WhiteBuffaloRTP.RTP_95).put(1, Arrays.asList(
				WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, 
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK));
		getReels().get(WhiteBuffaloRTP.RTP_95).put(2, Arrays.asList(
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD,
				WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_GODDESS, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING));
		getReels().get(WhiteBuffaloRTP.RTP_95).put(3, Arrays.asList(
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD,
				WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_GODDESS));
		getReels().get(WhiteBuffaloRTP.RTP_95).put(4, Arrays.asList(
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE,
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, WhiteBuffaloConfig.SYMBOL_RE, 
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, 
				WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, WhiteBuffaloConfig.SYMBOL_WILD, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_JACK, 
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, 
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN, 
				WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_BONUS,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, 
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, 
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, 
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_GODDESS, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, 
				WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_URN, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, 
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK, 
				WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_KING, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_BONUS, WhiteBuffaloConfig.SYMBOL_ACE, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_TOMAHAWK));
		getReels().get(WhiteBuffaloRTP.RTP_95).put(5, Arrays.asList(
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_URN, 
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_URN, 
				WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, 
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_URN, 
				WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_KING,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_QUEEN, 
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, 
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_LOGO,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN, 
				WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_KING, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, 
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_GODDESS, WhiteBuffaloConfig.SYMBOL_QUEEN, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_JACK, 
				WhiteBuffaloConfig.SYMBOL_TOMAHAWK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, 
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_LOGO, WhiteBuffaloConfig.SYMBOL_ACE,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO, WhiteBuffaloConfig.SYMBOL_QUEEN, 
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_URN,
				WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_JACK, WhiteBuffaloConfig.SYMBOL_ACE, WhiteBuffaloConfig.SYMBOL_ACE, 
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_WHITEBUFFALO,
				WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_KING, WhiteBuffaloConfig.SYMBOL_URN, WhiteBuffaloConfig.SYMBOL_JACK,
				WhiteBuffaloConfig.SYMBOL_QUEEN, WhiteBuffaloConfig.SYMBOL_QUEEN));
		
		initStops.put(WhiteBuffaloRTP.RTP_92, new HashMap<Integer, List<Integer>>());
        initStops.get(WhiteBuffaloRTP.RTP_92).put(0, Arrays.asList(120,120,120,120,130));
        initStops.get(WhiteBuffaloRTP.RTP_92).put(1, Arrays.asList(86,86,78,82,81));
        initStops.get(WhiteBuffaloRTP.RTP_92).put(2, Arrays.asList(100,100,150,100,100));
        initStops.get(WhiteBuffaloRTP.RTP_92).put(3, Arrays.asList(111,116,116,109,107));
        initStops.get(WhiteBuffaloRTP.RTP_92).put(4, Arrays.asList(127,135,127,127,130));
        
        initStops.put(WhiteBuffaloRTP.RTP_94, new HashMap<Integer, List<Integer>>());
        initStops.get(WhiteBuffaloRTP.RTP_94).put(0, Arrays.asList(120,120,120,120,130));
        initStops.get(WhiteBuffaloRTP.RTP_94).put(1, Arrays.asList(86,86,78,82,81));
        initStops.get(WhiteBuffaloRTP.RTP_94).put(2, Arrays.asList(100,100,100,100,100));
        initStops.get(WhiteBuffaloRTP.RTP_94).put(3, Arrays.asList(111,116,116,109,107));
        initStops.get(WhiteBuffaloRTP.RTP_94).put(4, Arrays.asList(127,135,127,127,130));
        
        initStops.put(WhiteBuffaloRTP.RTP_95, new HashMap<Integer, List<Integer>>());
        initStops.get(WhiteBuffaloRTP.RTP_95).put(0, Arrays.asList(120,120,120,120,130));
        initStops.get(WhiteBuffaloRTP.RTP_95).put(1, Arrays.asList(86,86,78,82,81));
        initStops.get(WhiteBuffaloRTP.RTP_95).put(2, Arrays.asList(100,100,150,100,100));
        initStops.get(WhiteBuffaloRTP.RTP_95).put(3, Arrays.asList(111,116,116,109,107));
        initStops.get(WhiteBuffaloRTP.RTP_95).put(4, Arrays.asList(127,135,127,127,130));
	}

	public int displayHeight() {
		return WhiteBuffaloConfig.DISPLAY_HEIGHT;
	}

	public Map<String, String> symbolMap() {
		return WhiteBuffaloConfig.SYMBOL_MAP;
	}

	public List<String> reel(Object level, int reel) {
		return getReels().get(level).get(reel);
	}

	public int numReels() {
		return WhiteBuffaloConfig.NUM_REELS;
	}

	public Map<String,String> reverseMap(){
		return WhiteBuffaloConfig.REVERSE_MAP;
	}

	public static Map<Object, Map<Integer,List<String>>> getReels() {
		return reels;
	}
	
	public static Map<Integer, List<Integer>> getInitStops(Object level) {
    	return initStops.get(level);
    }
}
